import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [choice, setChoice] = useState('');
  const [output, setOutput] = useState('');

  const handleChoiceChange = (event) => {
    setChoice(event.target.value);
  };

  async function onSubmit(event){
    event.preventDefault();

    try {
      const response = await fetch("/api/Scenario", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ userChoice: choice }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`);
      }

      setOutput(data.result);
      setAnimalInput("");
    } catch(error) {
      // Consider implementing your own error handling logic here
      console.error(error);
      alert(error.message);
    }
  }

  return (
    <>
      <Head>
        <title>Squirrlideology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Scenario</h1>
          <input
            type="text"
            value={choice}
            onChange={handleChoiceChange}
            placeholder="What should you do?"
          />
          <button onClick={onSubmit}>Generate Scenario</button>
          <div>
            <h2>Generated Scenario:</h2>
            <p>{output}</p>
          </div>
        </div>
      </main>
    </>
  )
}
