import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');

  const handleInputChange = (event) => {
    setInput(event.target.value);
  };

  const handleSubmit = async () => {
    try {
      const response = await axios.post('./api/scenario', {
        prompt: input,
      });

      setOutput(response.data.generated_text);
    } catch (error) {
      console.error('Error making API call:', error);
    }
  };

  return (
    <>
      <Head>
        <title>Squirrly Scenario</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Next.js App with OpenAI API</h1>
          <input
            type="text"
            value={input}
            onChange={handleInputChange}
            placeholder="Enter a prompt"
          />
          <button onClick={handleSubmit}>Generate Scenario</button>
          <div>
            <h2>Generated Scenario:</h2>
            <p>{output}</p>
          </div>
        </div>
      </main>
    </>
  )
}
